apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitrack-dev
  namespace: argocd
spec:
  project: fitrack
  source:
    repoURL: <YOUR_FITRACK_INFRA_GIT_URL>
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fitrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
