apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitrack
  namespace: argocd
spec:
  project: fitrack
  source:
    repoURL: <YOUR_FITRACK_INFRA_GIT_URL>
    targetRevision: main
    path: apps/children
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
