apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitrack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivakk/fitrack-infra.git
    targetRevision: main
    path: apps/children
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
